### ISSUE TITLE
seqSetter implicit is too wide and clashes with writer for Map

### ISSUE THREAD

**Issue by cppexpert** [osinka/subset2#13]
It's regarding pull request I proposed https://github.com/osinka/subset2/pull/12

I was able to pinpoint the issue only after I specified `-Xlog-implicits` parameter.

Looks like `seqSetter` implicit is too wide and clashes with new writer for Map. Here is what scalac says

```
[info] ambiguous implicit values:
[info]  both method seqSetter in object BsonWritable of type [T](implicit w: com.osinka.subset.BsonWritable[T])com.osinka.subset.BsonWritable[Traversable[T]]
[info]  and method mapSetterStringKey in object BsonWritable of type [V](implicit vw: com.osinka.subset.BsonWritable[V])com.osinka.subset.BsonWritable[Map[String,V]]
[info]  match expected type com.osinka.subset.BsonWritable[scala.collection.immutable.Map[String,List[Double]]]
```

I'm not sure why Scala can't pick up more specific implicit but as a fix I propose to replace `seqSetter` with implicit for `Seq`. Any objections ?

**Comment by alaz** [comment]
Fixed by #14
